### ISSUE TITLE
Info kevin bernabe

### ISSUE THREAD

**Issue by kevinjB168** [SistemasTecTlaxiaco/infografia-kevinjB168#2]
[Infografia kevin bernabe Juárez_20240826_155246_0000.pdf](https://github.com/user-attachments/files/16754189/Infografia.kevin.bernabe.Juarez_20240826_155246_0000.pdf)

**Comment by josealfredo79** [comment]
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:12/14
Referencias:13/14
Presentación:13/14
Calificación Final: 19/2
